Add support for ceph clusters using podman
stackhpc/ansible-collection-cephadm pull request #142
Opened 2024-03-27 17:35 UTC by technowhizz

2024-04-12 06:55 UTC, PC-Admin commented
This PR looks excellent, thank you for taking the time to create it.

2024-04-15 13:54 UTC, markgoddard requested changes

2024-04-15 13:54 UTC, markgoddard commented on roles/cephadm/tasks/pkg_debian.yml
> +  become: true
Is there some scope creep here? I'm not sure this role should be installing docker or podman - next it will need to configure them etc.

2024-04-18 18:55 UTC, technowhizz commented on roles/cephadm/tasks/pkg_debian.yml
> +  become: true
The reason I included this is because if a node isnt part of the kolla inventory like it is at some customers, then we wont have docker/podman installed on the machine.

2024-04-19 08:39 UTC, markgoddard commented on roles/cephadm/tasks/pkg_debian.yml
> +  become: true
That's a fair reason. However we need to keep roles limited in scope, which requires them to have prerequisites. IMO a prerequisite for this role should be that either docker or podman is installed.

Note that from Antelope Kayobe installs docker, not Kolla Ansible. So you could add your hosts to the `docker` group, if they are not in it already.

2024-04-25 10:58 UTC, technowhizz commented on roles/cephadm/tasks/pkg_debian.yml
> +  become: true
Ah fair enough so from antelope we can move the nodes into the docker group, in which case I guess we can remove the above

2024-04-25 11:06 UTC, mnasiadka commented on roles/cephadm/tasks/pkg_debian.yml
> +  become: true
I think this is not the purpose of this role - I'm fine with adding a precheck though.

2024-04-29 10:57 UTC, markgoddard approved these changes

2024-06-10 11:46 UTC, merged