Add support for pools, users, CRUSH rules and EC profiles
stackhpc/ansible-collection-cephadm pull request #44
Opened 2022-01-25 09:42 UTC by cityofships

Closes #35

2022-01-25 10:10 UTC, markgoddard requested changes
I stopped reviewing, lots of files need updating

2022-01-25 10:10 UTC, markgoddard commented on plugins/module_utils/cephadm_common.py
> +# Copyright 2021, StackHPC, Ltd.
While it's good to keep the RedHat copyright, we should probably mention where these files were adapted from.

2022-01-25 10:10 UTC, markgoddard commented on roles/ec_profiles/defaults/main.yml
> +cephadm_crush_rules: []
ec_profiles

2022-01-25 10:10 UTC, markgoddard commented on roles/keys/README.md
> +* `cephadm_keys`: A list of pools to define
s/pools/keys/

2022-03-24 15:44 UTC, markgoddard requested changes

2022-03-24 15:44 UTC, markgoddard commented on roles/pools/README.md
> +* `osds`
Just `mons`

2022-03-24 15:44 UTC, markgoddard commented on roles/pools/README.md
> +All Ceph hosts must be in the `ceph` group.
Delete

2022-03-24 15:44 UTC, markgoddard commented on roles/pools/README.md
> +              state: absent
Are these valid?

2022-03-24 15:44 UTC, markgoddard commented on roles/keys/README.md
> +All Ceph hosts must be in the `ceph` group.
Not really

2022-03-24 15:44 UTC, markgoddard commented on roles/ec_profiles/README.md
> +# keys
Whole readme is wrong

2022-03-24 15:44 UTC, markgoddard commented on plugins/modules/cephadm_crush_rule.py
> +version_added: "1.6.0"
1.4.0?

2022-03-24 15:44 UTC, markgoddard commented on plugins/modules/cephadm_ec_profile.py
> +version_added: "1.6.0"
1.4.0

2022-03-24 15:44 UTC, markgoddard commented on plugins/modules/cephadm_ec_profile.py
> +        required: true
false

2022-03-24 15:44 UTC, markgoddard commented on plugins/modules/cephadm_ec_profile.py
> +        required: true
false

2022-03-24 15:44 UTC, markgoddard commented on plugins/modules/cephadm_key.py
> +version_added: "1.6.0"
1.4.0

2022-03-24 15:44 UTC, markgoddard commented on plugins/modules/cephadm_key.py
> +    secret: "AQAin8tUUK84ExAA/QgBtI7gEMWdmnvKBzlXdQ=="
Not used?

2022-03-24 15:44 UTC, markgoddard commented on plugins/modules/cephadm_key.py
> +    name: "my_key""
Double double quote

2022-04-27 11:05 UTC, mnasiadka commented on roles/pools/README.md
> +* `osds`
Done

2022-04-27 11:12 UTC, mnasiadka commented on plugins/modules/cephadm_key.py
> +    secret: "AQAin8tUUK84ExAA/QgBtI7gEMWdmnvKBzlXdQ=="
Used in L111?

2022-04-27 11:15 UTC, mnasiadka commented on roles/pools/README.md
> +              state: absent
Updated.

2022-05-09 11:13 UTC, mnasiadka approved these changes

2022-05-09 11:18 UTC, cityofships commented
This is already a long-running one, let's address the feedback in a follow up.

2022-05-09 11:49 UTC, merged