Enable bootstrap for single host
stackhpc/ansible-collection-cephadm pull request #58
Opened 2022-07-29 14:53 UTC by piersharding

This PR adds some things that have helped with build test environments with less post deploy manual config:
* add arbitrary bootstrap arguments
* add generic post bootstrap config commands
* parameterise distribution release (required on Jammy or future newish releases)
* make ssh_user specification optional
* add generic post bootstrap and osd commands

Signed-off-by: Piers Harding <piers@ompka.net>

2022-08-01 08:17 UTC, markgoddard requested changes
Thanks Piers

2022-08-01 08:17 UTC, markgoddard commented on roles/cephadm/tasks/config.yml
> +---
Wondering if this ought to be a separate role?

2022-08-01 08:17 UTC, markgoddard commented on roles/cephadm/tasks/pkg_debian.yml
> +    repo: "deb https://download.ceph.com/debian-{{ item }}/ {{ cephadm_ansible_distribution_release }} main"
Maybe cephadm_apt_repo_dist or similar would be a more descriptive name?

2022-08-01 08:17 UTC, markgoddard commented on roles/commands/templates/cluster.yml.j2
> +{% for host in groups['ceph'] %}
Added by mistake?

2022-08-01 08:17 UTC, markgoddard commented on roles/commands/vars/main.yml
> +---
Won't hurt, but unnecessary.

2022-08-01 08:17 UTC, markgoddard commented on roles/commands/README.md
> +All Ceph hosts must be in the `ceph` group.
Not strictly necessary for this role

2022-08-01 10:18 UTC, piersharding commented on roles/commands/templates/cluster.yml.j2
> +{% for host in groups['ceph'] %}
yes - will remove

2022-08-01 10:18 UTC, piersharding commented on roles/commands/vars/main.yml
> +---
as above - a bad copy

2022-08-01 10:18 UTC, piersharding commented on roles/cephadm/tasks/pkg_debian.yml
> +    repo: "deb https://download.ceph.com/debian-{{ item }}/ {{ cephadm_ansible_distribution_release }} main"
yes - quite right.

2022-08-01 10:18 UTC, piersharding commented on roles/cephadm/tasks/config.yml
> +---
It could be - it is practically identical to `commands`, but it is things that happen after bootstrap but before anything else such as using the pools role.  In light of that I think that there would be a case for wanting to then be able to call `commands` twice (or more) - bracketing other roles - how would you approach that ?

2022-08-01 10:20 UTC, piersharding commented on roles/commands/README.md
> +All Ceph hosts must be in the `ceph` group.
ah, ok - `pools` does a similar thing to this

2022-08-01 12:09 UTC, piersharding commented on roles/cephadm/tasks/config.yml
> +---
OK - so it seems to work well enough if I go with a plan of including the commands role multiple times, so I have removed configs.

2022-08-02 08:44 UTC, markgoddard reviewed
Almost there

2022-08-02 08:44 UTC, markgoddard commented on roles/commands/tasks/main.yml
> +- include_tasks: "commands.yml"
Could you move the task in here?

2022-08-02 08:44 UTC, markgoddard commented on roles/commands/tasks/commands.yml
> +- name: Perform custom commands
Don't really need a block here since it's a single task

2022-08-02 17:46 UTC, piersharding commented on roles/commands/tasks/main.yml
> +- include_tasks: "commands.yml"
done

2022-08-02 18:26 UTC, piersharding commented on roles/commands/tasks/commands.yml
> +- name: Perform custom commands
OK

2022-08-02 18:35 UTC, piersharding commented
Hi - I resolved a merge conflict with upstream, but it would be good if you consider whether it still does what you intended - thanks.

2022-08-02 19:01 UTC, markgoddard approved these changes

2022-08-02 19:02 UTC, markgoddard commented
Thanks @piersharding

2022-08-02 19:08 UTC, merged