Add osds_nomemtune group
stackhpc/ansible-collection-cephadm pull request #71
Opened 2022-10-12 09:44 UTC by mnasiadka

Automatically adds _no_autotune_memory label for those hosts.

2022-10-12 09:47 UTC, mnasiadka commented
label documented here: https://docs.ceph.com/en/latest/cephadm/host-management/#special-host-labels

2022-10-12 10:55 UTC, markgoddard commented on roles/cephadm/templates/cluster.yml.j2
> +  - _no_autotune_memory
Would it be more flexible to allow specifying a list of labels for any host?

2022-10-12 11:07 UTC, mnasiadka commented on roles/cephadm/templates/cluster.yml.j2
> +  - _no_autotune_memory
Might be, but it's a) more work b) change of approach c) we already manage _admin in that way more or less - I don't think there will be many more of those labels in future (and _no_schedule is rather a temporary thing, so we don't need to manage it here).

2022-10-12 12:52 UTC, mnasiadka commented on roles/cephadm/templates/cluster.yml.j2
> +  - _no_autotune_memory
So basically what you propose is to have a host/group variables that is "cephadm_labels" and apply them in addition to those that we already have for mons/mgrs/osds/rgws?

2022-10-13 14:05 UTC, markgoddard requested changes

2022-10-18 15:11 UTC, markgoddard approved these changes

2022-10-18 15:50 UTC, merged