Fix deployment with FQDN hostnames
stackhpc/ansible-collection-cephadm pull request #93
Opened 2023-04-07 03:53 UTC by priteau

cephadm demands that the name of the host given via ceph orch host add
equals the output of hostname on remote hosts [1].

In Ansible, the output of hostname is obtained with the nodename fact.
The hostname variable only returns the name until the first dot. See a
similar change in kolla-ansible for more details [2].

[1] https://docs.ceph.com/en/quincy/cephadm/host-management/#cephadm-fqdn
[2] https://review.opendev.org/c/openstack/kolla-ansible/+/660463

2023-04-07 08:50 UTC, grzegorzkoper approved these changes
LGTM

2023-04-07 08:52 UTC, mnasiadka commented
> LGTM

Are we sure it will not impact existing deployments?

2023-04-07 08:59 UTC, grzegorzkoper commented
When thinking about it more, we should actually test it before merging. Existing deployments might have already short names in inventory, and this might double the inventory entries .

2023-04-07 12:32 UTC, priteau commented
> > LGTM
> 
> Are we sure it will not impact existing deployments?

In theory it shouldn't have impact, because if you managed to deploy already, it means your hostname command returns the short name, which should be the same as the existing hostname being used. But we should test it before merging.

2023-04-17 08:18 UTC, markgoddard approved these changes

2023-04-25 07:48 UTC, mnasiadka submitted a review, later dismissed

2023-04-25 07:48 UTC, mnasiadka commented on roles/cephadm/tasks/osds.yml
> +         ceph orch daemon add osd {{ ansible_facts.nodename }}:{{ item }}
Don't we need –allow-fqdn-hostname in bootstrap.yml?
I think it would be better if we would have a variable cephadm_use_fqdn and add --allow-fqdn-hostname and use nodename based on this.

2023-04-25 07:50 UTC, mnasiadka commented on roles/cephadm/tasks/osds.yml
> +         ceph orch daemon add osd {{ ansible_facts.nodename }}:{{ item }}
Not mentioning that 3 years ago cephadm team wanted to remove fqdn support - https://tracker.ceph.com/issues/44039

2023-04-25 08:25 UTC, priteau commented on roles/cephadm/tasks/osds.yml
> +         ceph orch daemon add osd {{ ansible_facts.nodename }}:{{ item }}
> Don't we need –allow-fqdn-hostname in bootstrap.yml?
> I think it would be better if we would have a variable cephadm_use_fqdn and add --allow-fqdn-hostname and use nodename based on this.

Yes, I also set this option separately. I can add an option to enable it. However as I explained in the commit message, `ansible_facts.nodename` should work for all setups (to be verified).

2023-05-18 12:24 UTC, markgoddard approved these changes

2023-05-18 12:25 UTC, markgoddard requested changes
Lots of `var-naming[no-role-prefix]` failures - add to skip list?

2023-08-01 13:28 UTC, cityofships commented
Rebased

2023-08-03 08:57 UTC, cityofships commented on roles/cephadm/tasks/osds.yml
> +         ceph orch daemon add osd {{ ansible_facts.nodename }}:{{ item }}
`--allow-fqdn-hostname` can be passed via `cephadm_bootstrap_additional_parameters` so the change's looking good. Also tested on one live environment 👍

2023-08-03 08:58 UTC, merged